name: Jay Orten
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
url: https://jayorten.github.io/

collections:
  reviews:
    output: true
    permalink: /reviews/:year/:month/:day/:title
